---
kind: pipeline
type: kubernetes
name: build
metadata:
  namespace: ci

platform:
  os: linux
  arch: amd64
steps:
- name: build_image_and_push
  image: plugins/docker
  settings:
    username: drone-ci
    password:
      from_secret: REG_PASS
    repo: registry.rocket.chat/statuscentral
    registry: registry.rocket.chat
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - ${DRONE_COMMIT_BRANCH/\//-}
  when:
    event:
    - push
    - tag
