---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build_n_push
  image: plugins/ecr
  settings:
    access_key:
      from_secret: ecr_username
    secret_key:
      from_secret: ecr_password
    repo: 652890069108.dkr.ecr.us-east-1.amazonaws.com/statuscentral
    registry: 652890069108.dkr.ecr.us-east-1.amazonaws.com
  when:
    event:
    - push
    - tag