# We should probably not include this
dataPath: ./databasefiles/
website:
  title: Rocket.Chat
  headerBgColor: "#5f5f5f"
services:
  - name: service1
    description: My awesome service
  - name: service2
    description: My second awesome service