# We should probably not include this
dataPath: ./databasefiles/
authToken: abc123def456
website:
  title: Rocket.Chat
  headerBgColor: "#2e343e"
services:
  - name: service1
    description: My awesome service
  - name: service2
    description: My second awesome service