# We should probably not include this
dataPath: ./databasefiles/
authToken: abc123def456
website:
  title: Rocket.Chat
  headerBgColor: "#2e343e"
  cacheBreaker: v1
  daysToAggregate: 7
services:
  - name: Marketplace
    description: The Rocket.Chat Marketplace API server.
  - name: Push Gateway
    description: The Rocket.Chat Push Gateway server.
