version: "3"

services:
  statuscentral:
    container_name: statuscentral
    image: statuscentral:edge
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=5050
    command: -configFile=/usr/local/statuscentral/statuscentral.compose.yaml
    restart: unless-stopped
    volumes:
      - statuscentral_vol:/usr/local/statuscentral/db
      - ${PWD}/statuscentral.compose.yml:/usr/local/statuscentral/statuscentral.compose.yaml
    ports:
      - 5050:5050
volumes:
  statuscentral_vol:
