version: "3"

services:
  statuscentral:
    container_name: statuscentral
    image: statuscentral:edge
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=5050
        - CONF_FILE=statuscentral.compose.yml
    restart: unless-stopped
    volumes:
      - statuscentral_vol:/usr/local/statuscentral
    ports:
      - 5050:5050
volumes:
  statuscentral_vol:
