name: Build and Test

on:
  pull_request:

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
