name: Build and Push

on:
  push:
    tags:
      - v*
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-push:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Login to Docker Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            rocketchat/statuscentral:${{ github.sha }}
